runs:
  using: "composite"
  steps:
    - name: Clean LE at docker image
      shell: bash
      if: inputs.clean_le == 'clean_le' || github.event.inputs.clean_le == 'clean_le'
      run: |
        rm -rf ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/.stamps
        rm -rf ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/*
        echo "ls: $(ls -la ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }})"
