runs:
  using: "composite"
  steps:
    - name: Checkout LibreELEC Git
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 2
        repository: "LibreELEC/LibreELEC.tv"
        path: "LibreELEC.tv"
