runs:
  using: "composite"
  steps:
    - name: Upload files
      shell: bash
      if: inputs.upload == 'upload' || github.event.inputs.upload == 'upload'
      run: |
        ls -lah ${{ env.BASEDIR }}/target
        scp -P ${{ secrets.PORT }} ${{ env.BASEDIR }}/target/*.{zip,img.gz} \
        ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.UPLOAD_TARGET }}
