runs:
  using: "composite"
  steps:
    - name: Build LE Addons using docker
      shell: bash
      run: |
        cd LibreELEC.tv
        docker run --rm -v ${{ env.BASEDIR }}/sources:/sources \
                        -v ${{ env.BASEDIR }}/target:/target \
                        -v ${{ env.BASEDIR }}/build-root:/build-root \
                        -v `pwd`:/build \
                        -w /build -i \
                        -e PROJECT=${{ env.PROJECT }} \
                        -e ARCH=${{ env.ARCH }} \
                        -e DEVICE=${{ env.DEVICE }} \
                        -e ONELOG=no -e LOGCOMBINE=never \
                        -e BUILD_DIR=${{ env.build_dir }} \
                        -e CCACHE_DISABLE=${{ env.CCACHE_DISABLE }} \
                        gh-${{ github.run_id }} scripts/create_addon script.config.vdr
        docker image rm -f gh-${{ github.run_id }}
      continue-on-error: true
