inputs:
  PACKAGE_NAME:
    description: "package name to update"
    required: true
  PACKAGE_VERSION:
    description: "version to update to"
    required: false
  IS_REPO:
    description: "is this a repository update?"
    required: false
  app-id:
    description: "GitHub App ID"
    required: true
  private-key:
    description: "GitHub App private key"
    required: true
name: automated-package-update
description: "Update package version and create a pull request"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        #fetch-depth: 1
        persist-credentials: false
        repository: LibreELEC/LibreELEC.tv
        ref: master
        path: LibreELEC-pr/
    - name: Debug input values
      shell: bash
      run: |
        echo "PACKAGE_NAME: ${{ inputs.PACKAGE_NAME }}"
        echo "PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}"
        echo "IS_REPO: ${{ inputs.IS_REPO }}"
        FULL_APP_ID="${{ inputs.app-id }}"
        FULL_PRIVATE_KEY="${{ inputs.private-key }}"
        echo "--------------------------------"
        echo "PEM: ${FULL_PRIVATE_KEY:0:4}"
        echo "APP_ID: ${FULL_APP_ID:0:4}"
        echo "--------------------------------"
    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: LibreELEC
        repositories: pr-actions
    - name: Configure git
      shell: bash
      run: |
        cd LibreELEC-pr/
        git config user.name "LibreELECBot"
        git config user.email "LibreELECBot@users.noreply.github.com"
    - name: Normalize version
      shell: bash
      run: |
        cd LibreELEC-pr/
        # shorten the version if it is a git sha256 hash
        # add a full version variable as well
        PACKAGE_VERSION="${{ inputs.PACKAGE_VERSION }}"
        PACKAGE_VERSION_FULL="${{ inputs.PACKAGE_VERSION }}"
        if [[ "${PACKAGE_VERSION}" =~ ^[0-9a-fA-F]{40}$ ]]; then
          # Git SHA-256 hash to short hash
          PACKAGE_VERSION="${PACKAGE_VERSION:0:7}"
        fi
        # if IS_REPO is true use date as versioning
        if [[ "${{ inputs.IS_REPO }}" == "yes" ]]; then
          PACKAGE_VERSION="$(date '+%Y%m%d-%H%M%S')"
          PACKAGE_VERSION_FULL="${PACKAGE_VERSION}"
          echo "IS_REPO=yes" >> $GITHUB_ENV
        fi
        # export vars and debug output
        echo "IS_REPO: ${{ inputs.IS_REPO }}"
        echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
        echo "PACKAGE_VERSION_FULL=${{ inputs.PACKAGE_VERSION }}" >> $GITHUB_ENV
        echo "PACKAGE_VERSION: ${PACKAGE_VERSION}"
        echo "PACKAGE_VERSION_FULL: ${PACKAGE_VERSION_FULL}"
    - name: Run update script
      shell: bash
      run: |
        cd LibreELEC-pr/
        echo "running update for package..."
        echo "package name: ${{ inputs.PACKAGE_NAME }}"
        echo "package version: ${{ env.PACKAGE_VERSION_FULL }}"
        echo "is repo: ${{ inputs.IS_REPO }}"
        echo "$IS_REPO"
        if [[ "${IS_REPO}" == "yes" ]]; then
          ./tools/update-pkg "${{ inputs.PACKAGE_NAME }}"
        else
          ./tools/update-pkg "${{ inputs.PACKAGE_NAME }}" "$PACKAGE_VERSION_FULL"
        fi
    - name: Push branch to pr-actions
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        cd LibreELEC-pr/
        FULL_GH_TOKEN="${{ steps.app-token.outputs.token }}"
        echo "---0---"
        echo "FULL_GH_TOKEN: ${FULL_GH_TOKEN:0:4}"
        git checkout -b "pr-automated/${{ inputs.PACKAGE_NAME }}-${PACKAGE_VERSION}"
        echo "---1---"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/LibreELEC/pr-actions.git
        echo "rev-parse before push"
        git rev-parse --is-shallow-repository
        # echo "Unshallowing repository..."
        # git fetch --unshallow
        echo "Pushing branch to remote..."
        git push -f origin "pr-automated/${{ inputs.PACKAGE_NAME }}-${PACKAGE_VERSION}"
        echo "---3---"
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        cd LibreELEC-pr/
        # get the LE base version
        LE_VERSION=$(sed -nE 's/^[[:space:]]*OS_VERSION="([^"]+)".*/\1/p' distributions/LibreELEC/version)
        echo "---1---"
        FULL_GH_TOKEN="${{ steps.app-token.outputs.token }}"
        echo "---2---"
        echo "FULL_GH_TOKEN: ${FULL_GH_TOKEN:0:4}"
        # create the pr
        # --header "Authorization: token ${GH_TOKEN}" \
        gh api repos/LibreELEC/LibreELEC.tv/pulls \
          -f title="[LE${LE_VERSION}] ${{ inputs.PACKAGE_NAME }}: update to ${PACKAGE_VERSION}" \
          -f body="Automated update of ${{ inputs.PACKAGE_NAME }} to version ${PACKAGE_VERSION} using tools/update-pkg."
          -f head="pr-automated/${{ inputs.PACKAGE_NAME }}-${PACKAGE_VERSION}" \
          -f base="master"
