runs:
  using: "composite"
  steps:
    - name: Create docker image for build
      shell: bash
      run: |
        ls
        pwd
        cd LibreELEC.tv
        sed -i -e "s/RUN adduser/RUN adduser --uid $(id -u)/" tools/docker/focal/Dockerfile
        # workaround below until buildsystem does not require local cc
        sed -i -e "/^USER docker/i RUN ln -s /usr/bin/gcc-10 /usr/bin/cc" tools/docker/focal/Dockerfile
        sed -i -e 's/^CCACHE_CACHE_SIZE=.*/CCACHE_CACHE_SIZE="30G"/' config/options
        docker build --pull -t gh-${{ github.run_id }} tools/docker/focal
