name: build-LE11
on:
  workflow_dispatch:
    inputs:
      le_periodic_version:
        description: "Version and Perodic builds"
        default: nightly
        required: true
        type: choice
        options:
          - nightly
          - official
      gitref_to_build:
        description: "gitref tag or hash to build"
        default: libreelec-11.0
        required: true
        type: string
      target:
        description: "targets to build"
        default: all
        required: true
        type: choice
        options:
          - all
          - A64.arm
          - H3.arm
          - H5.arm
          - H6.arm
          - R40.arm
          - AMLGX.arm
          - Generic.x86_64
          - Generic-legacy.x86_64
          - RK3288.arm
          - RK3328.arm
          - RK3399.arm
          - RPi2.arm
          - RPi4.arm
          - RPi5.arm

env:
  clean_le: no_clean_le
  debug: debug
  ephemeral: ephemeral
  upload: upload

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Checkout LibreELEC/LibreELEC.tv and check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: libreelec-11.0
          fetch-depth: 2
          repository: "${{ github.repository_owner }}/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: print latest_commit of checked out LibreELEC/LibreELEC.tv
        run: |
          cd LibreELEC.tv
          git rev-parse HEAD
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          cd LibreELEC.tv
          test -z "$(git rev-list --after='24 hours' $(git rev-parse HEAD))" && echo "should_run=false" >> $GITHUB_OUTPUT
          exit 0

  # Allwinner
  A64_arm-11_0:
    name: "A64.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'A64.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: A64_arm-11_0
      project: Allwinner
      arch: arm
      device: A64
      targetbuilddir: build.LibreELEC-A64.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  H3_arm-11_0:
    name: "H3.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'H3.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: H3_arm-11_0
      project: Allwinner
      arch: arm
      device: H3
      targetbuilddir: build.LibreELEC-H3.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  H5_arm-11_0:
    name: "H5.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'H5.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: H5_arm-11_0
      project: Allwinner
      arch: arm
      device: H5
      targetbuilddir: build.LibreELEC-H5.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  H6_arm-11_0:
    name: "H6.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'H6.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: H6_arm-11_0
      project: Allwinner
      arch: arm
      device: H6
      targetbuilddir: build.LibreELEC-H6.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  R40_arm:
    name: "R40.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'R40.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: R40_arm-11_0
      project: Allwinner
      arch: arm
      device: R40
      targetbuilddir: build.LibreELEC-R40.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit

  # Amlogic
  AMLGX_arm-11_0:
    name: "AMLGX.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'AMLGX.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: AMLGX_arm-11_0
      project: Amlogic
      arch: arm
      device: AMLGX
      targetbuilddir: build.LibreELEC-AMLGX.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit

  # Generic
  Generic_x86_64-11_0:
    name: "Generic.x86_64 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'Generic.x86_64' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: Generic_x86_64-11_0
      project: Generic
      arch: x86_64
      device: Generic
      targetbuilddir: build.LibreELEC-Generic.x86_64-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 20G
      version: "11.0"
      file_extension: img.gz,ova,tar
    secrets: inherit

  # Generic-legacy
  Generic-legacy_x86_64-11_0:
    name: "Generic-legacy.x86_64 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'Generic-legacy.x86_64' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: Generic-legacy_x86_64-11_0
      project: Generic
      arch: x86_64
      device: Generic-legacy
      targetbuilddir: build.LibreELEC-Generic-legacy.x86_64-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 20G
      version: "11.0"
      file_extension: img.gz,ova,tar
    secrets: inherit

  # Rockchip
  RK3288_arm-11_0:
    name: "RK3288.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RK3288.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RK3288_arm-11_0
      project: Rockchip
      arch: arm
      device: RK3288
      targetbuilddir: build.LibreELEC-RK3288.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  RK3328_arm-11_0:
    name: "RK3328.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RK3328.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RK3328_arm-11_0
      project: Rockchip
      arch: arm
      device: RK3328
      targetbuilddir: build.LibreELEC-RK3328.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  RK3399_arm-11_0:
    name: "RK3399.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RK3399.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RK3399_arm-11_0
      project: Rockchip
      arch: arm
      device: RK3399
      targetbuilddir: build.LibreELEC-RK3399.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit

  # RPi
  RPi2_arm-11_0:
    name: "RPi2.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RPi2.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RPi2_arm-11_0
      project: RPi
      arch: arm
      device: RPi2
      targetbuilddir: build.LibreELEC-RPi2.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  RPi4_arm-11_0:
    name: "RPi4.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RPi4.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RPi4_arm-11_0
      project: RPi
      arch: arm
      device: RPi4
      targetbuilddir: build.LibreELEC-RPi4.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
  RPi5_arm-11_0:
    name: "RPi5.arm 11.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RPi5.arm' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE11.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-11.0' }}
      group: RPi5_arm-11_0
      project: RPi
      arch: arm
      device: RPi5
      targetbuilddir: build.LibreELEC-RPi5.arm-11.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "11.0"
      file_extension: img.gz,tar
    secrets: inherit
