name: clean-hotdog
on:
  workflow_dispatch:
    inputs:
      run_clean:
        description: 'Run a hotdog clean'
        default: no_run_clean
        required: true
        type: choice
        options:
          - no_run_clean
          - run_clean
env:
  TZ: Australia/Melbourne

jobs:
  clean_hotdog:
    runs-on: ubuntu-latest

    steps:
      - name: Run Clean
        if: github.events.inputs.run_clean == 'run_clean'
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rm ${{ secrets.UPLOAD_TARGET }}/addons/*/*.zip"
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rmdir ${{ secrets.UPLOAD_TARGET }}/addons/*"
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rm ${{ secrets.UPLOAD_TARGET }}/*.ova"
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rm ${{ secrets.UPLOAD_TARGET }}/*.tar"
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            "rm ${{ secrets.UPLOAD_TARGET }}/*.img.gz"
