name: make-image
on:
  workflow_call:
    inputs:
      clean_le:
        # This setting is only used (makes sense) when builds are NOT ephemeral
        description: 'Should the workflow clean the /build-root'
        default: no_clean_le
        required: true
        type: string
      debug:
        description: 'Provide debug output from GHA run'
        default: no_debug
        required: true
        type: string
      ephemeral:
        description: 'Target and build-root are ephemeral'
        default: ephemeral
        required: true
        type: string
      upload:
        description: 'Upload the images to the release server'
        default: no_upload
        required: true
        type: string
      buildcmd:
        description: 'build command to run'
        default: 'make image'
        required: true
        type: string
      gitref:
        description: 'git branch or hash to build'
        default: libreelec-10.0
        required: true
        type: string
      group:
        description: 'concurrency group'
        default: Generic_x86_64-10_0
        required: true
        type: string
      project:
        description: 'target project'
        default: Generic
        required: true
        type: string
      arch:
        description: 'target arch'
        default: x86_64
        required: true
        type: string
      device:
        description: 'target device'
        default: ""
        required: false
        type: string
      targetbuilddir:
        description: 'TARGETBUILDDIR'
        default: ""
        required: true
        type: string
      buildperiodic:
        description: 'BUILD_PERIODIC'
        default: nightly
        required: true
        type: string
      ccachecachesize:
        description: 'CCACHE_CACHE_SIZE'
        default: 10G
        required: true
        type: string
      version:
        description: 'version code used in TARGETBUILDDIR'
        default: ""
        required: false
        type: string
      fileextns:
        description: 'file extns to copy to webserver'
        default: img.gz,ova,tar
        required: true
        type: string

env:
  TZ: Australia/Melbourne
  BASEDIR: /var/media/DATA/github-actions
  # Distro Target Variables
  PROJECT: ${{ inputs.project }}
  ARCH: ${{ inputs.arch }}
  DEVICE: ${{ inputs.device }}
  TARGETBUILDDIR: ${{ inputs.targetbuilddir }}
  BUILD_PERIODIC: ${{ inputs.buildperiodic }}

concurrency:
  group: ${{ inputs.group }}
  cancel-in-progress: false

jobs:
  build_image:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gitref }}
          fetch-depth: 2
          repository: "LibreELEC/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: customise the checked out git repository
        run: |
          cd LibreELEC.tv
          sed -i -e "s/RUN adduser/RUN adduser --uid $(id -u)/" tools/docker/focal/Dockerfile
          # workaround below until buildsystem does not require local cc
          #sed -i -e "/^USER docker/i RUN ln -s /usr/bin/gcc-10 /usr/bin/cc" tools/docker/focal/Dockerfile
          sed -i -e 's/^CCACHE_CACHE_SIZE=.*/CCACHE_CACHE_SIZE="${{ inputs.ccachecachesize }}"/' config/options

      - name: build official release
        if: inputs.buildperiodic == 'official'
        run: |
          cd LibreELEC.tv
          sed -i -e 's/LIBREELEC_VERSION="devel"/LIBREELEC_VERSION="${{ inputs.gitref }}"/' distributions/LibreELEC/version
          echo "OFFICIAL=\"yes\"" >> distributions/LibreELEC/version
          echo "building official ${{ inputs.gitref }}"

      - name: Create docker image for build - tools/docker/focal
        run: |
          cd LibreELEC.tv
          docker build --pull -t gh-${{ github.run_id }} tools/docker/focal

      - name: Prepare the LibreELEC.tv directory - setup /sources
        run: |
          cd LibreELEC.tv
          # create links that will be used from within the docker containers
          [ ! -h sources ] && ln -s /sources .

      - name: Prepare the LibreELEC.tv directory - do not leave files behind
        if: inputs.ephemeral == 'ephemeral'
        run: |
          cd LibreELEC.tv
          # set the build_dir=/build
          echo "build_dir=/build" >> $GITHUB_ENV
          echo "CCACHE_DISABLE=1" >> $GITHUB_ENV
      - name: Prepare the LibreELEC.tv directory - use /build-root and /target
        if: inputs.ephemeral == 'no_ephemeral'
        run: |
          cd LibreELEC.tv
          # create links that will be used from within the docker containers
          [ ! -h target ] && ln -s /target .
          # set the build_dir=/build-root - for NON ephemeral builds
          echo "build_dir=/build-root" >> $GITHUB_ENV

      - name: Display environment
        if: inputs.debug == 'debug'
        run: |
          cd LibreELEC.tv
          echo "pwd: $(pwd)"
          echo "id: $(id)"
          echo "whoami: $(whoami)"
          echo "docker images: $(docker images)"
          echo "ls: $(ls -la)"
          echo
          echo "inputs.clean_le: ${{ inputs.clean_le }}"
          echo "inputs.debug: ${{ inputs.debug }}"
          echo "inputs.ephemeral: ${{ inputs.ephemeral }}"
          echo "inputs.upload: ${{ inputs.upload }}"

      - name: Clean LE at docker image
        if: inputs.clean_le == 'clean_le'
        run: |
          rm -rf ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/.stamps
          rm -rf ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/*
          echo "ls: $(ls -la ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }})"

      - name: Build LE using docker
        run: |
          cd LibreELEC.tv
          docker run --rm -v ${{ env.BASEDIR }}/sources:/sources \
                          -v ${{ env.BASEDIR }}/target:/target \
                          -v ${{ env.BASEDIR }}/build-root:/build-root \
                          -v `pwd`:/build \
                          -w /build -i \
                          -e PROJECT=${{ env.PROJECT }} \
                          -e ARCH=${{ env.ARCH }} \
                          -e DEVICE=${{ env.DEVICE }} \
                          -e ONELOG=no -e LOGCOMBINE=fail \
                          -e BUILD_DIR=${{ env.build_dir }} \
                          -e BUILD_PERIODIC=${{ env.BUILD_PERIODIC }} \
                          -e CCACHE_DISABLE=${{ env.CCACHE_DISABLE }} \
                          gh-${{ github.run_id }} ${{ inputs.buildcmd }}

      - name: prepare ephemeral artifacts
        if: inputs.ephemeral == 'ephemeral'
        run: |
          cd LibreELEC.tv
          mkdir -p ${{ env.TARGETBUILDDIR }}/artifact
          grep ^FAIL ${{ env.TARGETBUILDDIR }}/.threads/joblog | \
            awk '{ print $5, $12 }' | tr ':' '_' | \
              while read failedpkg failedlog
              do
                mv $(echo ${failedlog} | sed 's#/build/##') \
                  ${{ env.TARGETBUILDDIR }}/artifact/${{ env.TARGETBUILDDIR }}-${failedpkg}-$(echo ${failedlog} | sed 's#.*/##')
              done
      - name: prepare non-ephemeral artifacts
        if: inputs.ephemeral == 'no_ephemeral'
        run: |
          cd LibreELEC.tv
          mkdir -p ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/artifact
          grep ^FAIL ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/.threads/joblog | \
            awk '{ print $5, $12 }' | tr ':' '_' | \
              while read failedpkg failedlog
              do
                mv ${{ env.BASEDIR }}/${failedlog} \
                  ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/artifact/${{ env.TARGETBUILDDIR }}-${failedpkg}-$(echo ${failedlog} | sed 's#.*/##')
              done

      - name: upload failed artifacts - ephemeral
        if: inputs.ephemeral == 'ephemeral'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGETBUILDDIR }}-failed
          path: LibreELEC.tv/${{ env.TARGETBUILDDIR }}/artifact/
      - name: upload failed artifacts - no_ephemeral
        if: inputs.ephemeral == 'no_ephemeral'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGETBUILDDIR }}-failed
          path: ${{ env.BASEDIR }}/build-root/${{ env.TARGETBUILDDIR }}/artifact/

      - name: clean docker images and tags
        run: |
          cd LibreELEC.tv
          docker image rm -f gh-${{ github.run_id }}

      - name: Upload OFFICIAL Release
        if: (inputs.buildperiodic == 'official') && (inputs.upload == 'upload')
        run: |
          cd LibreELEC.tv
          echo "upload official ${{ inputs.gitref }}"
          # domsomething
      - name: Upload image
        if: (inputs.buildperiodic != 'official') && (inputs.upload == 'upload')
        run: |
          cd LibreELEC.tv
          ls -lahR target
          scp -P ${{ secrets.PORT }} target/*.{${{ inputs.fileextns }}} \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.UPLOAD_TARGET }}
