name: nightly-MASTER
on:
  # allows to run this workflow manually from the actions tab
  workflow_dispatch:
  schedule:
    # The times are specified in UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 14 * * *'

    # Performance
    # 12h20m - 14 May 2022 - AMD Ryzen 5 3600 (no .ccache) - 4 runners
    # 10h31m - 15 May 2022 - AMD Ryzen 5 3600 (no .ccache) - 4 runners - 1 failure on image with automake
env:
  TZ: Australia/Melbourne
  # these ENV variables are not used yet - need to get this working with the with statements below
  clean_le: no_clean_le
  debug: debug
  ephemeral: ephemeral
  upload: upload
      
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Checkout LibreELEC.tv/LibreELEC.tv and check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
          repository: "LibreELEC/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: print latest_commit of checked out LibreELEC.tv/LibreELEC.tv
        run: |
          cd LibreELEC.tv
          echo $(git rev-parse HEAD)
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          cd LibreELEC.tv
          test -z "$(git rev-list --after='24 hours' $(git rev-parse HEAD))" && echo "::set-output name=should_run::false"
        
  # Allwinner
  A64_arm:
    name: A64.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: A64_arm
      project: Allwinner
      arch: arm
      device: A64
      targetbuilddir: build.LibreELEC-A64.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  H3_arm:
    name: H3.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: H3_arm
      project: Allwinner
      arch: arm
      device: H3
      targetbuilddir: build.LibreELEC-H3.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  H5_arm:
    name: H5.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: H5_arm
      project: Allwinner
      arch: arm
      device: H5
      targetbuilddir: build.LibreELEC-H5.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  H6_arm:
    name: H6.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: H6_arm
      project: Allwinner
      arch: arm
      device: H6
      targetbuilddir: build.LibreELEC-H6.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # Amlogic
  AMLGX_arm:
    name: AMLGX.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: AMLGX_arm
      project: Amlogic
      arch: arm
      device: AMLGX
      targetbuilddir: build.LibreELEC-AMLGX.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # Generic
  Generic_x86_64:
    name: Generic.x86_64
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: Generic_x86_64
      project: Generic
      arch: x86_64
      device: Generic
      targetbuilddir: build.LibreELEC-Generic.x86_64-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 20G
      version: '11.0'
      fileextns: img.gz,ova,tar
    secrets: inherit

  # NXP
  iMX6_arm:
    name: iMX6.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: iMX6_arm
      project: NXP
      arch: arm
      device: iMX6
      targetbuilddir: build.LibreELEC-iMX6.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  iMX8_arm:
    name: iMX8.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: iMX8_arm
      project: NXP
      arch: arm
      device: iMX8
      targetbuilddir: build.LibreELEC-iMX8.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # Qualcomm
  Dragonboard_arm:
    name: Dragonboard.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: Dragonboard_arm
      project: Qualcomm
      arch: arm
      device: Dragonboard
      targetbuilddir: build.LibreELEC-Dragonboard.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # Rockchip
  RK3288_arm:
    name: RK3288.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: RK3288_arm
      project: Rockchip
      arch: arm
      device: RK3288
      targetbuilddir: build.LibreELEC-RK3288.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  RK3328_arm:
    name: RK3328.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: RK3328_arm
      project: Rockchip
      arch: arm
      device: RK3328
      targetbuilddir: build.LibreELEC-RK3328.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  RK3399_arm:
    name: RK3399.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: RK3399_arm
      project: Rockchip
      arch: arm
      device: RK3399
      targetbuilddir: build.LibreELEC-RK3399.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # RPi
  RPi2_arm:
    name: RPi2.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: RPi2_arm
      project: RPi
      arch: arm
      device: RPi2
      targetbuilddir: build.LibreELEC-RPi2.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
  RPi4_arm:
    name: RPi4.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: RPi4_arm
      project: RPi
      arch: arm
      device: RPi4
      targetbuilddir: build.LibreELEC-RPi4.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit

  # Samsung
  Exynos_arm:
    name: Exynos.arm
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/make-image.yml@main
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: 'make image'
      gitref: master
      group: Exynos_arm
      project: Samsung
      arch: arm
      device: Exynos
      targetbuilddir: build.LibreELEC-Exynos.arm-11.0-nightly
      buildperiodic: nightly
      ccachecachesize: 10G
      version: '11.0'
      fileextns: img.gz,tar
    secrets: inherit
