name: nightly-MASTER
on:
  # allows to run this workflow manually from the actions tab
  workflow_dispatch:
env:
  TZ: Australia/Melbourne
  clean_le: false
  upload: false
  #upload: true
  ephemeral_within: true
      
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
          repository: "LibreELEC/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        
  # Allwinner
  libreelec-A64_arm:
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/libreelec-A64_arm.yml@main
    with:
      clean_le: false
      upload: false
      ephemeral_within: true
  libreelec-H3_arm:
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/libreelec-H3_arm.yml@main
    with:
      clean_le: false
      upload: false
      ephemeral_within: true
  libreelec-H5_arm:
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/libreelec-H5_arm.yml@main
    with:
      clean_le: false
      upload: false
      ephemeral_within: true
  libreelec-H6_arm:
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/libreelec-H6_arm.yml@main
    with:
      clean_le: false
      upload: false
      ephemeral_within: true

  # Amlogic
  libreelec-AMLGX_arm:
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    uses: LibreELEC/actions/.github/workflows/libreelec-AMLGX_arm.yml@main
    with:
      clean_le: false
      upload: false
      ephemeral_within: true
