name: nightly-LE10
on:
  # allows to run this workflow manually from the actions tab
  workflow_dispatch:
  schedule:
    # The times are specified in UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 7 * * *'

env:
  TZ: Australia/Melbourne
  # these ENV variables are not used yet - need to get this working with the with statements below
  clean_le: no_clean_le
  debug: debug
  ephemeral: ephemeral
  upload: upload
      
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Checkout LibreELEC.tv/LibreELEC.tv and check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: libreelec-10.0
          fetch-depth: 2
          repository: "LibreELEC/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: print latest_commit of checked out LibreELEC.tv/LibreELEC.tv
        run: |
          cd LibreELEC.tv
          echo $(git rev-parse HEAD)
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          cd LibreELEC.tv
          test -z "$(git rev-list --after='24 hours' $(git rev-parse HEAD))" && echo "::set-output name=should_run::false"
        
  # Generic
  Generic_x86_64-10_0:
    runs-on: ubuntu-latest
    name: Build Generic.x86_64-10.0
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
    - name: make-image
      # Use the location in the repository (without action.yml)
      # Checkout the repository first
      # Otherwise the workflow won't be able to find the action
      uses: ./.github/actions/make-image
      with:
        clean_le: no_clean_le
        debug: debug
        ephemeral: ephemeral
        upload: upload
        buildcmd: 'make image'
        gitref: libreelec-10.0
        group: Generic_x86_64-10_0
        project: Generic
        arch: x86_64
        # device: Generic ### LE10 does not support DEVICE for PROJECT=Generic
        #         make sure it is set to empty string
        device: ''
        targetbuilddir: build.LibreELEC-Generic.x86_64-10.0-nightly
        buildperiodic: nightly
        ccachecachesize: 30G
        version: '10.0'
        fileextns: img.gz,ova,tar
        sec-host: ${{ secrets.HOST }}
        sec-port: ${{ secrets.PORT }}
        sec-username: ${{ secrets.USERNAME }}
        sec-upload-target: ${{ secrets.UPLOAD_TARGET }}
