name: Update repositories
on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to update
        required: true
        type: choice
        options:
          - LibreELEC/amlogic-boot-fip
          - LibreELEC/brcmfmac_sdio-firmware
          - LibreELEC/dt-overlays
          - LibreELEC/dvb-firmware
          - LibreELEC/eventlircd
          - LibreELEC/iwlwifi-firmware
          - LibreELEC/meson-firmware
          - LibreELEC/misc-firmware
          - LibreELEC/script.config.vdr
          - LibreELEC/service.libreelec.settings
          - LibreELEC/wlan-firmware
      BASE_BRANCH:
        description: Branch to checkout from the fork and PR base branch on the target repository
        required: false
        default: master
jobs:
  check-repo-update:
    runs-on: ubuntu-24.04
    if: github.repository == 'LibreELEC/actions'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Map repository choice to package matrix
        id: set-matrix
        shell: bash
        env:
          REPO: ${{ github.event.inputs.repository }}
        run: |
          echo "Selected repo: $REPO"
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)
          case "$REPO" in
            "LibreELEC/service.libreelec.settings")
              REPO_NAME="LibreELEC-settings"
              ;;
          esac
          updated_packages="${REPO_NAME}"
          pair=$(echo "$updated_packages" | jq -Rn -c '[inputs | split(" ")] | map({ name: .[0] })')
          echo "matrix=$pair" >> $GITHUB_OUTPUT
      - name: Job summary
        shell: bash
        run: |
          echo "### 📌 Updating these Packages" >> $GITHUB_STEP_SUMMARY
          {
            echo "| Package |"
            echo "|---------|"
            echo '${{ steps.set-matrix.outputs.matrix }}' | jq -r '.[] | "| \(.name) |"'
          } >> "$GITHUB_STEP_SUMMARY"
  call-package-update:
    needs: check-repo-update
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.check-repo-update.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: ${{ github.repository_owner }}/actions
      - name: Log matrix entry
        run: |
          echo "Package:  ${{ matrix.name }}"
      - name: Package version bump and PR
        uses: ./.github/actions/package_version_bump_and_pr_changes
        with:
          PACKAGE_NAME: ${{ matrix.name }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          BASE_BRANCH: ${{ github.event.inputs.BASE_BRANCH }}
