runs:
  using: "composite"
  steps:
    - name: Prepare the LibreELEC.tv directory - use /build-root and /target
      shell: bash
      if: inputs.ephemeral == 'no_ephemeral' || github.event.inputs.ephemeral == 'no_ephemeral'
      run: |
        cd LibreELEC.tv
        # create links that will be used from within the docker containers
        [ ! -h target ] && ln -s /target .
        # set the build_dir=/build-root - for NON ephemeral builds
        echo "build_dir=/build-root" >> $GITHUB_ENV
